[gcp_service_account]
type = "service_account"
project_id = "manasaroha"
private_key_id = "09d973e33d993b31fc865797e51731a26a90d271"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2JIZYff9IavrNdsPovy7/CB4rf8qm1r3fe2hK/rnYyt2mXtzN8tbDOPmPyggdd2XjHHOJett2snTfOGwcN5oyCCvlQaaTf0MzUv/lQ5VM0HZzLRiWvbjoU7YiKmvBJOMfZJK5I5TEfyOO0FyepfoelLi6hzm2Q2LtUyQSs8/0dPJdySrxpJngD+a7sb0gV5+yw1vuMEJeMdIvyQQ7QBNAb6cf6AlzHzW7PKpLoSUXRF4x6zNMiwB40Msvfcw0uD23qh+FYzsAZdCv7/paTO1zWGfnJgqQ5BE+noMPmWU2Xz0Xu6+kYaEYh0toGsRrf9zU12oiUlke5R/MYUpPAg03AgMBAAECggEAKnRF+h9YHt2MmtJpZHkXb6tJOPNe3VdlR09g5kYMNGtIkYw/5CMLitJfXPQGwzN+xJpvlaZUvAxpcFQa4tLU9n9wF84fEPcTR0W7zojbpl1alor21b/f9wr4A2um1QyPgdQz3MJd3RUTSSjoxbPDIlig3B1DxudbCh0cZd2ShZRN237cwPWYbu1oj8PB1jz8O6Wvhs6CkeR/JJ7BkPcV37MgrwyI4M558sV5OlRl4qhYFO1n1XPbkk6KWrXvpBbNxpIR86NRF+2sj+6PzXE8LZpcnKP3b/QB5/oydHsdzN2bqCBs+p7q7TqM5LCehxPnfFLb5m8v86Ow4OUP3ZyfmQKBgQDh7Y1qXXyu7yiRJlXdHwot5R74k+6/3gpaujruGl/YxJRDK8qrdGz0BFICJdmPUqucmvSToPZtZ+/F01MtaYNphBUQtICfCSOkiD4exAgZaI+xfB8y4j0eN7DVWo+eq3rhkPM1RhWq+k9sAdPSNyXpzigT+bdo3vnjGLLXnIktmQKBgQDOYv+kddmdHvFhpZwRcZ1xhkjF2lfgZM12aw6qal6NEzkXWIndgeMawR/EAzITW6HRmSaO3QygTXxMJ1RNVBogPRIC9sXBRn1qS46AQm6ZBScC1qR3eJBYDuD31CIQFKsM20E5TSEGPvlNKFx+joG9/0v+oWscT8ddTggUFQOzTwKBgQCi4E52IyWzO+mEEx4NxsXg5nBYhtW1bw8J735yj4MP1FCKyHRY/RtbJA43TDA3WkMsKK4wC/f8UdUTSlGJyKqblERXgbnEbaNLh4k5RtwL7UzCiJg5Z87mDQIoHhyyKC/zlDsx6e/PDpvZYsvhni5wC1brZ7jpGu8N4I12UXy36QKBgEuW4LCYZTpxsdCkujN9XD/PAepNHPBXmxTrAvURfk3HI5rUV7IkN0x+PScqUHXckrjUkdWzSkOP/Z1arjqgOe1i0Kz7OtSd/6MlxyxcqGstAuu8N4J2Ss+lq2m5bTxchYVw7EOTZywFdoN26+GCSiyPS4MYFcXJxmf7A2RvieprAoGAfTQgucBn6JdC0fHcTJeyI5W4LuiwFwC4ld+y+cSEfBLw0wjrNirF50L+D31fM6Z+XLLLrIW0/3oV+vAhumNJDoLICiICC6Tcf+ppp+/wnsbe4V/VZFyBVxOLZXgPoPLNQ76RJzJZ7p9YFfhM9bQnA8Mt3WPKwXZNK9K3vzNIko0=
-----END PRIVATE KEY-----"""
client_email = "manasaroha-sheets-access@manasaroha.iam.gserviceaccount.com"
client_id = "110899129135677329215"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/manasaroha-sheets-access%40manasaroha.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[sheet_id]
sheet_id = "1EyJimNqxXhh5rFabGHOyUidbDaZgslQecOOjOSJuSpk"

[openrouter_api_key]
openrouter_api_key = "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"

